app_index:
    path: /
    controller: App\Controller\GlobalController::index

app_actualites:
    path: /actualites
    controller: App\Controller\ActualiteController::index

app_actualites_view:
    path:     /actualite/{slug}/{id}
    defaults: { _controller: App\Controller\ActualiteController::view }
    requirements:
        slug: ([a-z-0-9]*)
        id: \d+

app_youtubes:
    path: /videos
    controller: App\Controller\YoutubeController::index

app_logout:
    path: /logout
